// layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { dmSans } from '@/lib/font';
import { cn } from '@/lib/utils/cn';
import Header from '@/components/nav/Header';

import { GoogleOAuthProvider } from '@react-oauth/google';

import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          dmSans.className,
          'antialiased '
        )}
      >
          <Header />
        <div className="flex flex-col">
          <GoogleOAuthProvider clientId="...">
            <main className="flex-grow">{children}</main>
          </GoogleOAuthProvider>
        </div>
          <Footer />
      </body>
    </html>
  );
}
