// layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { dmSans } from '@/lib/font';
import { cn } from '@/lib/utils/cn';
import Header from '@/components/nav/Header';

import { GoogleOAuthProvider } from '@react-oauth/google';

import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(dmSans.className, 'flex flex-col min-h-screen')}>
        <GoogleOAuthProvider clientId="214122998362-8gc20qq486bsnigkugj7fh09du0dm9hm.apps.googleusercontent.com">
          <Header />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
